# tfcmt Configuration used for posting Terraform GitHub Summaries
# https://suzuki-shunsuke.github.io/tfcmt/config
embedded_var_names: []
ci:
  pr: []
  owner: []
  repo: []
  sha: []
  link: []
  vars: {}
templates:
  apply_title: |
    {{ if eq .ExitCode 1}}
    ## Apply Failed for `{{.Vars.component}}` in `{{.Vars.stack}}`!
    
    [![apply](https://shields.io/badge/APPLY-FAILED-critical?style=for-the-badge)](#user-content-apply) 
    {{ end }}
    {{- if eq .ExitCode 0}}
    ##Apply Succeeded for `{{.Vars.component}}` in `{{.Vars.stack}}` 
    
    [![apply](https://shields.io/badge/APPLY-SUCCESS-success?style=for-the-badge)](#user-content-apply)
    {{ end }}

  result: |
    <details><summary><a id="result" />{{if .Result}}{{ .Result }}{{end}}</summary>

    <br/>
    To reproduce this locally, run:<br/><br/>

terraform:
  apply:
    template: |
      {{template "apply_title" .}}

      {{template "result" .}}
      ```shell
      atmos terraform apply {{.Vars.component}} -s {{.Vars.stack}}
      ```
      </details>

      <details><summary><a id="apply" />Terraform <strong>Apply</strong> Summary</summary>
      {{wrapCode .CombinedOutput}}
      </details>
    when_parse_error:
      template: |
        {{template "apply_title" .}}

        Failed to parse the result.

        <details><summary>Result</summary>
        {{wrapCode .CombinedOutput}}
        </details>
